site_name: Centralized Docs 
repo_name: 'williln/central-docs'
repo_url: 'https://github.com/williln/central-docs'


nav:
  - Intro: 'index.md'
  - django-email-relay: '!include ./django-email-relay/mkdocs.yml'
  - wagtail-heroicons: '!include ./wagtail-heroicons/mkdocs.yml'

plugins:
  - monorepo

theme:
  name: material
  language: 'en'
  font:
    text: 'Circular'
    code: 'Inconsolata'

extra:
  repo_icon: 'github'


markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true


